### ISSUE TITLE
'env' does not work in config files

### ISSUE THREAD

**Issue by relefant** [mdreizin/gatsby-plugin-robots-txt#117]
This works fine if put in gatsby-config.js. The result being a robots.txt with `Disallow: /` in it.

```
        resolveEnv: () => process.env.NODE_ENV,
        env: {
          development: {
            policy: [{ userAgent: '*', disallow: ['/'] }],
          },
          production: {
            policy: [{ userAgent: '*', disallow: ['/'] }],
          },
        },
```

But if I create a config file and reference it:

gatsby-config.js
```
configFile: 'robots-txt.config.js',
```

robots-txt.config.js
```
        resolveEnv: () => process.env.NODE_ENV,
        env: {
          development: {
            policy: [{ userAgent: '*', disallow: ['/'] }],
          },
          production: {
            policy: [{ userAgent: '*', disallow: ['/'] }],
          },
        },
```

then the policies in the env object are ignored. The result being a robots.txt with `Allow: /` in it.

**Comment by mdreizin** [comment]
It is designed to work only using `gatsby-config.js`. As a solution, you may different `robots-txt.config.js` by setting `configFile` for particular environment.
