### ISSUE TITLE
Peer Dependency Warning When Used With Gatsby V2.x

### ISSUE THREAD

**Issue by Undistraction** [mdreizin/gatsby-plugin-robots-txt#22]
Upgrading a Gatsby v1.x project to use Gatsby v2.x where the project uses this plugin results in a peer dependency warning in NPM, because of this plugin's peer dependency on Gatsby v1, which [excludes major versions](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004):

```javascript
"peerDependencies": {
    "gatsby": "^1.0.0"
  },
```

I don't think there is anything in V2 that should cause a problem with this plugin.

**Comment by mdreizin** [comment]
@Undistraction You can ignore this message for now, because it is compatible with v2.
