### ISSUE TITLE
Vulnerability [ Prototype Pollution]

### ISSUE THREAD

**Issue by AsathalMannan** [mdreizin/gatsby-plugin-robots-txt#241]
**Package:** yargs-parser
**Patched-in:** >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2
**Dependency of:** gatsby-plugin-robots-txt
**Path:** gatsby-plugin-robots-txt > generate-robotstxt > meow > yargs-parser
**More-info:**  (https://npmjs.com/advisories/1500)

**Comment by mvantol1** [comment]
The underlying dependency is already updated in #246.

**Comment by mvantol1** [comment]
Is it possible to make a new release?

**Comment by mdreizin** [comment]
@AsathalMannan Thanks for the report. I am working on a new release. It will be available within 1 hours. /cc @mvantol1.

**Comment by mdreizin** [comment]
@AsathalMannan @mvantol1 Please upgrade to 1.5.1.
