### ISSUE TITLE
Gatsby try to load gatsby-node.js source in a non-existent path

### ISSUE THREAD

**Issue by x86chi** [mdreizin/gatsby-plugin-robots-txt#273]
```log
UNHANDLED REJECTION ENOENT: 
no such file or directory, open '/node_modules/gatsby-plugin-robots-txt/src/gatsby-node.js'
```

Gatsby didn't load root directory of plugin `gatsby-plugin-robots-txt/gatsby-node.js`

I've try two gatsby-plugin-robots-txt version: 1.5.1, 1.5.0

Gatsby CLI version: 2.12.34
Gatsby version: 2.22.9

**Comment by luka-bacic** [comment]
Any updates on this since this PR? https://github.com/mdreizin/gatsby-plugin-robots-txt/pull/296 

The bug is still happening

**Comment by dw-srohrlack** [comment]
I was able to work around that issue by creating a local plugin in plugins/custom-gatsby-plugin-robots-txt/ (see https://www.gatsbyjs.com/docs/creating-plugins/) with the following gatsby-node.js file in that plugin:

`
const origPath = require.resolve('./../../node_modules/gatsby-plugin-robots-txt/gatsby-node.js');
const orig = require(origPath);
exports.onPostBuild = orig.onPostBuild;
`

Inside gatsby-config.js I changed the plugin name from "gatsby-plugin-robots-txt" to "custom-gatsby-plugin-robots-txt" so the configuration for the custom plugin get's passed.

**Comment by luka-bacic** [comment]
Thank you for the workaround @dw-srohrlack ! I will try it out when I can, and hopefully it will help future readers until this issue is resolved
