### ISSUE TITLE
Default usage

### ISSUE THREAD

**Issue by zslabs** [mdreizin/gatsby-plugin-robots-txt#28]
👋 Thanks for creating this! With the default usage:

`plugins: ['gatsby-plugin-robots-txt']`

Running `gatsby develop` or `gatsby build` doesn't seem to be actually generating the `robots.txt` file anywhere. I started going into the plugin option and setting paths, etc; but I'm not actually seeing any response. Is the default output `./static/robots.txt`?

**Comment by mdreizin** [comment]
Hello @zslabs! It ned to add some missing props:

```js
siteMetadata: {
   siteUrl: 'https://www.example.com'
}
```

Let me know if it works for you.

**Comment by zslabs** [comment]
@mdreizin Thanks for the reply! Hm, that is pretty odd. I already have that in there (pull that in through a few different areas on the site). I don't get any console errors or warnings, maybe something good to add if it can't grab some part of the config it is expecting/defaulting to?

**Comment by niklaslavrell** [comment]
@zslabs after running `gatsby build` you should be able to find it in `./public/robots.txt`.

**Comment by zslabs** [comment]
> @zslabs after running `gatsby build` you should be able to find it in `./public/robots.txt`.

🤦‍♂️ Wooord. Thanks, really appreciate it!
