### ISSUE TITLE
how to add additional info like  # Algolia-Crawler-Verif in robots.txt file

### ISSUE THREAD

**Issue by kailash-choudhary-thoughtspot** [mdreizin/gatsby-plugin-robots-txt#507]

**Comment by panzacoder** [comment]
+1 for this information, not seeing a way to add a string to the file. Would be great if we could just add plain text as well instead of everything needing to be an object.

**Comment by mdreizin** [comment]
Unfortunately, it is not possible now.

Please update `robots.txt` after the build by using a plugin or a script.
