### ISSUE TITLE
No support for multiple sitemaps?

### ISSUE THREAD

**Issue by Vincentgr** [mdreizin/gatsby-plugin-robots-txt#85]
Why not make `sitemaps` an array instead? Multiple sitemap entries **are** allowed according to the specification.

https://developers.google.com/search/reference/robots_txt

> [absoluteURL] points to a Sitemap, Sitemap Index file or equivalent URL. The URL does not have to be on the same host as the robots.txt file. **Multiple sitemap entries may exist**. As non-group-member records, these are not tied to any specific user-agents and may be followed by all crawlers, provided it is not disallowed.

**Comment by thomasryu** [comment]
This seems to be solved already, just attempted using an array instead of a string and both sitemaps were printed on `/robots.txt`

**Comment by Vincentgr** [comment]
Fair enough, should have tried that myself. So perhaps the docs just need to be updated.

**Comment by mdreizin** [comment]
Guys, I am sorry. I am on vacation 🏖 and I will update the docs after I return 😎.

**Comment by M-ZubairAhmed** [comment]
Can i update the docs?

**Comment by mdreizin** [comment]
@M-ZubairAhmed Feel free to update ;)

**Comment by mdreizin** [comment]
@M-ZubairAhmed Thanks a lot for updating the documentation.
